version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    working_dir: /app
    image: node:20
    volumes:
      - ./client:/app
    command: ["npm","run","dev","--","--host","0.0.0.0"]
    ports:
      - "3000:5173"
    depends_on:
      - backend
